---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - blinkns.demo.io
  resources:
  - blinkns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - blinkns.demo.io
  resources:
  - blinkns/finalizers
  verbs:
  - update
- apiGroups:
  - blinkns.demo.io
  resources:
  - blinkns/status
  verbs:
  - get
  - patch
  - update
