apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "blinkns.name" . }}
  labels:
    {{- include "blinkns.labels" . | nindent 4 }}
rules:
  - apiGroups: ["blinkns.demo.io"]
    resources: ["blinknses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["blinkns.demo.io"]
    resources: ["blinknses/status", "blinknses/finalizers"]
    verbs: ["get", "update", "patch"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
