{{- if .Values.notifications.webhookUrl }}
apiVersion: v1
kind: Secret
metadata:
  name: blinkns-notification-webhook
  namespace: {{ .Values.operatorNamespace }}
  labels:
    {{- include "blinkns.labels" . | nindent 4 }}
type: Opaque
stringData:
  url: {{ .Values.notifications.webhookUrl | quote }}
{{- end }}
